IMAGE_ID = 'id'
OWNER_ID = 'owner_id'
CREATE_DATE = 'create_date'
CREATE_DAY_ID = 'create_day_id'

FILE_PATH = 'file_path'
FILE_SIZE = 'file_size'
IMAGE_HEIGHT = 'image_height'
IMAGE_WIDTH = 'image_width'
MIME_TYPE = 'mime_type'

APERTURE = 'aperture'
ARTIST = 'artist'
CAMERA_MAKE = 'camera_make'
CAMERA_MODEL = 'camera_model'
FOCAL_LENGTH = 'focal_length'
FOCAL_LENGTH_D = 'focal_length_denominator'
FOCAL_LENGTH_N = 'focal_length_numerator'
ISO_SPEED = 'iso_speed'
SHUTTER_SPEED = 'shutter_speed'
SHUTTER_SPEED_D = 'shutter_speed_denominator'
SHUTTER_SPEED_N = 'shutter_speed_numerator'

GPS_ALT = 'gps_alt'
GPS_DATE_TIME = 'gps_date_time'
GPS_LAT = 'gps_lat'
GPS_LON = 'gps_lon'
