version = '0.0.1'

TRIGGER_ERROR = 'TRIGGER_ERROR'
MONITORING_DSN = 'SENTRY_DSN'
OPERATING_ENV = 'OPERATING_ENV'
DATABASE_URL = 'DB_URL'
SOURCE_BUCKET = 'AWS_UPLOAD_BUCKET_NAME'

DEFAULT_REGION = 'us-east-1'
