version = '1.1.2'

FORCE_UPDATE = 'FORCE_UPDATE'  # env var, also include query string with `update` in it.
VERBOSE_LOGGING = 'VERBOSE_LOGGING'
TRIGGER_ERROR = 'TRIGGER_ERROR'
MONITORING_DSN = 'SENTRY_DSN'
OPERATING_ENV = 'OPERATING_ENV'
DATABASE_URL = 'DB_URL'
SOURCE_BUCKET = 'AWS_UPLOAD_BUCKET_NAME'

DEFAULT_REGION = 'us-east-1'
